service: aws-coldstart-nodejs6

provider:
  name: aws
  runtime: nodejs6.10

functions:
  memory-128:
    handler: handler.hello
    memorySize: 128
    events:
      - schedule: rate(4 hours)

  memory-256:
    handler: handler.hello
    memorySize: 256
    events:
      - schedule: rate(4 hours)

  memory-512:
    handler: handler.hello
    memorySize: 512
    events:
      - schedule: rate(4 hours)

  memory-1024:
    handler: handler.hello
    memorySize: 1024
    events:
      - schedule: rate(4 hours)

  memory-1536:
    handler: handler.hello
    memorySize: 1536
    events:
      - schedule: rate(4 hours)